apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deploy
  labels:
    app: node-app
spec:
  # Start with 2 copies of your application
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app-container
        # Your custom Node.js image
        image: docker.io/yvmr/nap1:latest 
        ports:
        - containerPort: 3000 # The port your Node.js application is listening on
